FROM apache/airflow:latest

USER root


RUN apt-get update && \
    apt-get -y install git && \
    apt-get -y install curl && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools unixodbc-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER airflow

# Add the 'airflow' user


# Give necessary permissions to the 'airflow' user
#RUN chown -R airflow:airflow /opt/airflow/logs

# Install the Github provider package
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

RUN pip install pycountry

RUN pip install airflow-code-editor

RUN pip install googleads
# RUN pip install airflow-editor


COPY tattoo_oauth2_desktop_client_secret_53343684005-hlrv507jks3lrepluuvrmta3ve7iuqp8.json /opt/airflow/tattoo_oauth2_desktop_client_secret_53343684005-hlrv507jks3lrepluuvrmta3ve7iuqp8.json


# Set the environment variable
ENV LD_LIBRARY_PATH=/opt/microsoft/msodbcsql17/lib64:$LD_LIBRARY_PATH
